// <auto-generated />
namespace LocadoraDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Primeira_Migracao_Locadora : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Primeira_Migracao_Locadora));
        
        string IMigrationMetadata.Id
        {
            get { return "202009060141191_Primeira_Migracao_Locadora"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
