// <auto-generated />
namespace LocadoraDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Ajuste_Relacionamento_Locacao_e_Filme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajuste_Relacionamento_Locacao_e_Filme));
        
        string IMigrationMetadata.Id
        {
            get { return "202009090256598_Ajuste_Relacionamento_Locacao_e_Filme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
